[tool.poetry]
name = "pythonstockmarket"
version = "0.1.0"
description = ""
authors = ["AritraRakshit <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
yfinance = "^0.1.59"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
